# site settings
title: Colin Stodd
name: Colin Stodd's personal website focused on his career in web application and mobile development
subtitle: Colin Stodd's Personal Website
email: cbstodd@harpua.co
description: Colin Stodd's personal website focused on his career in web application and mobile development
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colinstodd.com" # the base hostname & protocol for your site
author: Colin Stodd
street_address:
city: Annapolis
state: MD
zip_code:
country: United States of America
phone: 443-333-1031

# social settings
500px_url:
facebook_url: https://www.facebook.com/colin.stodd
github_url: https://github.com/cbstodd
googleplus_url: https://plus.google.com/u/0/+cbstodd
instagram_url: https://instagram.com/cbstodd
linkedin_url: https://www.linkedin.com/in/colin.stodd
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cbstodd
theme: solid_state_jekyll_theme

# Syntax Highlighting:
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# build settings
markdown: kramdown

collections:
  posts:
    output: true
    permalink: /posts/:categories/:path
  projects:
    output: true
    permalink: /projects/:category/:path
  image-gallery:
    output: false

menus:
  - Home: "/"
  - About: "/about.html"
  - Contact: "/#getInTouch"
  - Posts: "/posts.html"
  - Projects: "/projects.html"
  - Technologies: "/technologies.html"
  # - Generic: "/generic.html"
  # - Elements: "/elements.html"
  # - Log in: "#"
  # - Sign up: "#"

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-environment-variables
  - jekyll-redirect-from
  - jekyll-compress-images
  - jekyll-feed

    # SEO / META:
twitter:
  username: cbstodd
  card: summary_large_image

facebook:
  app_id: 792796074135713
  # publisher: 1234
  admins: colin.stodd

social:
  name: Colin Stodd
  links:
    - https://twitter.com/cbstodd
    - https://www.facebook.com/colin.stodd
    - https://www.linkedin.com/in/colin-stodd
    - https://github.com/cbstodd
    - https://medium.com/@cbstodd
    - https://www.instagram.com/cbstodd

webmaster_verifications:
  google: 1234
  # bing: 1234

disqus:
  shortname: colinstodd-v2

google:
  tag_manager:
    container_id: GTM-5KC3SGB

compress_images:
  images_path: "images/**/*.{gif,png,jpg,jpeg,svg}"


# ATOM Feed:
feed:
  collections:
    - posts
    - projects

# Env Variables:
RECAPTCHA_SITE_KEY: '6LcNQ8kZAAAAACJL-16GCA8EfkaizSE57L-ZX3Ct'
RECAPTCHA_SECRET_KEY: '6LcNQ8kZAAAAAOE6FDrD8j2JIregNJ_--HzA0vmd'
getFormId: '248d99c5-214c-4ffe-b8f7-f12be8720b59'
correctBotAnswer: 'cs'