# site settings
title: Colin Stodd
subtitle: Colin Stodd's Personal Website
email: cbstodd@harpua.co
description: Colin Stodd's personal website focused on his career in web application and mobile development
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://blog.colinstodd.com" # the base hostname & protocol for your site
author: cbstodd
street_address:
city: Annapolis
state: MD
zip_code: 21403
country: United States of America
phone: 443-333-1031

# social settings
500px_url:
facebook_url:
github_url: https://github.com/cbstodd
googleplus_url: https://plus.google.com/u/0/+cbstodd
instagram_url: https://instagram.com/cbstodd
linkedin_url: https://www.linkedin.com/in/colin.stodd
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cbstodd
theme: solid_state_jekyll_theme

# Syntax Highlighting:
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# build settings
markdown: kramdown

# collections:
#   projects:
#     output: true
#     permalink: /:collection/:title

# defaults:
#   - scope:
#       path: "posts/post"
#     values:
#       type: "post"
#   - scope:
#       path: "projects/project"
#     values:
#       type: "project"

menus:
  - Home: "/"
  - About: "/about"
  - Contact: "/contact"
  - Posts: "/posts"
  # - Projects: "/projects"
  # - Generic: "/generic.html"
  # - Elements: "/elements.html"
  # - Log in: "#"
  # - Sign up: "#"

sass:
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-environment-variables
  - jekyll-redirect-from

    # SEO / META:
twitter:
  username: cbstodd
  card: summary_large_image

facebook:
  app_id: site.env.FACEBOOK_APP_ID
  publisher: 1234
  admins: 1234

social:
  name: Colin Stodd
  links:
    - https://twitter.com/cbstodd
    - https://www.facebook.com/colin.stodd
    - https://www.linkedin.com/in/colin.stodd
    - https://github.com/cbstodd

webmaster_verifications:
  google: 1234
  bing: 1234
  alexa: 1234
  yandex: 1234
  baidu: 1234
